version: "3"
services:

  openwb:
    image: jonius/openwb:latest
    init: true
    container_name: openwb
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      TZ: "Europe/Berlin"
    ports:
      - "80:80"
      - "9001:9001"
    volumes:
      - app-volume:/var/www/html/openWB
      - ./mosquitto:/var/lib/mosquitto
        
volumes:
  app-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/data'
