version: "3"
services:

  openwb:
    image: jonius/openwb:latest
    init: true
    container_name: openwb
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      TZ: "Europe/Berlin"
    ports:
      - "80:80"
      - "9001:9001"
    volumes:
      - type: bind
        source: ./openwb.conf
        target: /var/www/html/openWB/openwb.conf
      - type: bind
        source: ./logdata
        target: /var/www/html/openWB/web/logging/data
      - type: bind
        source: ./mosquitto
        target: /var/lib/mosquitto